package com.example.servlet;

import com.google.gson.Gson;
import com.example.dao.TutorialDAO;
import com.example.model.Tutorial;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("/api/tutorials")
public class TutorialServlet extends HttpServlet {
    private final Gson gson = new Gson();
    private TutorialDAO tutorialDAO;

    @Override
    public void init() {
        this.tutorialDAO = new TutorialDAO();
    }

    private void setupCORS(HttpServletResponse resp) {
        resp.setHeader("Access-Control-Allow-Origin", "http://localhost:5173"); // Aligned with your frontend port
        resp.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
        resp.setHeader("Access-Control-Allow-Headers", "Content-Type");
        resp.setHeader("Access-Control-Allow-Credentials", "true");
    }

    @Override
    protected void doOptions(HttpServletRequest req, HttpServletResponse resp) {
        setupCORS(resp);
        resp.setStatus(HttpServletResponse.SC_OK);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        setupCORS(resp);
        resp.setContentType("application/json");
        resp.setCharacterEncoding("UTF-8");

        try {
            List<Tutorial> tutorials = tutorialDAO.getAllTutorials();
            resp.getWriter().write(gson.toJson(tutorials));
        } catch (Exception e) {
            resp.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            resp.getWriter().write("{\"status\":\"error\", \"message\":\"" + e.getMessage() + "\"}");
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        setupCORS(resp);
        resp.setContentType("application/json");
        resp.setCharacterEncoding("UTF-8");

        try {
            // Read JSON request
            StringBuilder jsonBuilder = new StringBuilder();
            try (java.io.BufferedReader reader = req.getReader()) {
                String line;
                while ((line = reader.readLine()) != null) {
                    jsonBuilder.append(line);
                }
            }

            String jsonString = jsonBuilder.toString();
            Tutorial newTutorial = gson.fromJson(jsonString, Tutorial.class);

            // Basic validation or ID generation if needed
            // If ID is auto-generated by MongoDB, we might not need to set it,
            // but Tutorial.java uses ObjectId which Mongo generates.
            // If specific logic needed:
            // newTutorial.setId(new org.bson.types.ObjectId());

            tutorialDAO.saveTutorial(newTutorial);

            resp.setStatus(HttpServletResponse.SC_CREATED);
            resp.getWriter().write(
                    gson.toJson(java.util.Map.of("status", "success", "message", "Tutorial added successfully")));
        } catch (Exception e) {
            resp.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            resp.getWriter().write("{\"status\":\"error\", \"message\":\"" + e.getMessage() + "\"}");
        }
    }
}